<%@ page contentType="text/plain;charset=UTF-8" %># Environment configuration generated by Greenpeace
# For project "${props.configuration.project.name}:${props.version1.name}" in environment "${props.configuration.environment1.name}"
<g:each var="prop" in="${props.effectiveProperties()}">${prop.key}=${prop.value}
</g:each>